### PR TITLE
Kubernetes integration

### PR DESCRIPTION
**Pull request by shokohsc**

### CODE REVIEW

**Comment by shokohsc** [comment]
Same as https://github.com/pawelmalak/flame/pull/72#issue-704030901
Not a javascript/typescript guy. maybe it can be improved, but it registers then display any enabled ingress as an application front-side.
That is something that bothers me, should it register in the database the application ? What happens when the application is removed ? Do we really need to go clean it up in the applications settings ui ?
Same goes for docker.
As you're using cache since latest release, couldn't we just retrieve from the api, docker or kubernetes applications, then merge with what was retrieved from the database ?

**Review by pawelmalak — APPROVED** [review]

**Comment by pawelmalak** [comment]
I think that custom ordering should be available for all apps, both manualy and automatically created. Please revert to previous version.

**Review by pawelmalak — CHANGES_REQUESTED** [review]
I think that custom ordering should be available for all apps, both manualy and automatically created. Please revert to previous version.

**Comment by shokohsc** [comment]
👍  on it

**Review by pawelmalak — APPROVED** [review]

**Comment by shokohsc** [comment]
I removed the `wip` commit because i think it needs more destruct to be working.

**Pull request merged**
