### PR TITLE
Remove fatal error from docker secrets

### LINKED ISSUE #242: [BUG]  Flame crashes after updating to version 2.1.1 while running on k3s.
**Deployment details:**
- App version [e.g. v1.7.4]: v2.1.1
- Platform [e.g. amd64, arm64, arm/v7]: arm64, amd64
- Docker image tag [e.g. latest, multiarch]: multiarch2.1.1

---

**Bug description:**

After updating to version 2.1.1, my previously-working flame installation has started crashing with the following error:
```
node:internal/fs/utils:344
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at /app/node_modules/docker-secret/dist/index.js:17:39
    at Array.forEach (<anonymous>)
    at getSecrets (/app/node_modules/docker-secret/dist/index.js:14:15)
    at Object.<anonymous> (/app/node_modules/docker-secret/dist/index.js:28:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/utils/init/initDockerSecrets.js:1:24)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
```
---

**Steps to reproduce:**

1. Start with a base k3s installation.
2. Deploy the following resource to the cluster:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flame
spec:
  selector:
    matchLabels:
      app: flame
  template:
    metadata:
      labels:
        app: flame
    spec:
      volumes:
        - name: flame-volume
          emptyDir: {}
      containers:
      - name: flame
        image: pawelmalak/flame:multiarch2.1.1
        ports:
        - containerPort: 5005
        volumeMounts:
        - mountPath: /app/data
          name: flame-volume
        env:
        - name: PASSWORD
          value: flame_password
```
3. Watch the logs of the newly-deployed pod.

### PR DESCRIPTION
**Pull request by IDevJoe**
This commit fixes #242 by catching the error thrown by getSecrets(). The underlying issue exists in docker-secret and has to do with the serviceAccount secret installed automatically by kubernetes.

### CODE REVIEW

**Comment by IDevJoe** [comment]
This fix is meant to be temporary to allow people to continue to use the latest version of flame until docker-secret is updated. All it does is convert a fatal error into a regular error.

**Comment by pawelmalak** [comment]
Did you test it? Beacuse it is the exact same thing I did (wrapped `initDockerSecrets` function body with try catch block) when the bug was first reported and according to [jojotastic777](https://github.com/pawelmalak/flame/issues/242#issuecomment-985466952) who tested the image, nothing has changed.

**Comment by IDevJoe** [comment]
I'm not gonna lie, the code was a tad rushed and I didn't have time to build and test it. The code I proposed here does not fix the issue unfortunately. I have opened hwkd/docker-secret#1, which has tested working code, and I was able to start Flame with it. I did post a temporary workaround in #242.

vmconnect_WWsSXm59wU

**Comment by pawelmalak** [comment]
It's still not working for me. I built new image from [IDevJoe:master](https://github.com/IDevJoe/flame) - `pawelmalak/flame:dev-alpha1`. I then tested it with normal Docker deployment - no surprises here, it works fine, same as `latest` and `multiarch` tags. Next I tried to run it on k3s cluster with:
```yml
# flame-k3s.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flame
spec:
  selector:
    matchLabels:
      app: flame
  template:
    metadata:
      labels:
        app: flame
    spec:
      volumes:
        - name: flame-volume
          emptyDir: {}
      containers:
      - name: flame
        image: pawelmalak/flame:dev-alpha1
        ports:
        - containerPort: 5005
        volumeMounts:
        - mountPath: /app/data
          name: flame-volume
        env:
        - name: PASSWORD
          value: flame_password
```

But it's still the same error:

```bash
# start
kubectl create -f flame-k3s.yml

# get logs
kubectl logs flame-55469bd596-tkbf9
node:internal/fs/utils:344
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:723:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at /app/node_modules/docker-secret/dist/index.js:17:39
    at Array.forEach (<anonymous>)
    at getSecrets (/app/node_modules/docker-secret/dist/index.js:14:15)
    at Object.<anonymous> (/app/node_modules/docker-secret/dist/index.js:28:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/utils/init/initDockerSecrets.js:1:24)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}

# list pods
kubectl get pods
NAME                     READY   STATUS             RESTARTS   AGE
flame-55469bd596-tkbf9   0/1     CrashLoopBackOff   6          9m30s
```

**Comment by IDevJoe** [comment]
@pawelmalak Try now

**Comment by pawelmalak** [comment]
Now it seems to be working fine.

**Comment by IDevJoe** [comment]
Commit c8436aa references the fixed docker-secret. Although it's not entirely ideal, the container could be built off of this until the pull on docker-secret is merged. If it comes down to it, and docker-secret seems abandoned, I'll more than likely just republish it on npm.

**Comment by hwkd** [comment]
Sorry folks, I didn't notice the PR made by @IDevJoe. My mind was quite preoccupied with work. I've merged the PR on hwkd/docker-secret and published it to npm.

**Comment by IDevJoe** [comment]
@pawelmalak The PR here [references my repository](https://github.com/pawelmalak/flame/pull/248/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L24). Since the root issue is now fixed, I'd recommend changing it back to the repository on npm.

Appreciate ya'll.

**Pull request merged**
